# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Issue Created Notification
on:
  issues:
    types: [opened, reopened]

jobs:
  notify:
    uses: ./.github/workflows/slack-notification.yml
    with:
      message: "New github issue: ${{ github.event.issue.html_url }}"
