# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Post an inline text message
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Leave a kind message after updates
    runs-on: ubuntu-latest
    steps:
      - name: Intentionally fail (for demo purposes)
        run: |
          echo "This step will fail intentionally"
          exit 1
          
      - name: Send GitHub Action data to a Slack workflow
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {"repo": "MPL", "status": "failed", "message": "Workflow has failed!"}
          webhook-type: webhook-trigger
