# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Post an inline text message
on:
  push:
    branches:
      - main
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "1"

  fail:
    runs-on: ubuntu-latest
    steps:
      - name: print 2
        run: |
          echo "3"
          exit 1
  
  notify:
    needs: [print, fail]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure message to a Slack workflow
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {"message": "MPL's daily CI failed!"}
          webhook-type: webhook-trigger
