# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Post an inline text message
on:
  push:
    branches:
      - main
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          echo "1"

  fail:
    runs-on: ubuntu-latest
    steps:
      - name: print 2
        run: |
          echo "3"
          exit 1
  
  notify:
    needs: [print, fail]
    if: ${{ failure() }}
    uses: ./.github/workflows/slack-notification.yml
    with:
      message: "workflow failed"
